// <auto-generated />
namespace BlazorApp1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddRooms : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddRooms));
        
        string IMigrationMetadata.Id
        {
            get { return "202101232036064_AddRooms"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
